name: better_selection
description: Web-like text selection. Built on super_editor
version: 0.0.1
publish_to: none
homepage: https://github.com/wilsonowilson/better_selection

environment:
  sdk: ">=2.12.0 <=3.3.10"

dependencies:
  flutter:
    sdk: flutter
  super_editor: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.1

flutter: null
